### ISSUE TITLE
error activate plugin

### ISSUE THREAD

**Issue by TecSecret** [weDevsOfficial/wp-project-manager#495]
Fatal error: Uncaught TypeError: Carbon\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in /home/host001r/public_html/wp-content/plugins/wedevs-project-manager/vendor/nesbot/carbon/src/Carbon/Carbon.php on line 559 and defined in /home/host001r/public_html/wp-content/plugins/wedevs-project-manager/vendor/nesbot/carbon/src/Carbon/Carbon.php:927 Stack trace: #0 /home/host001r/public_html/wp-content/plugins/wedevs-project-manager/vendor/nesbot/carbon/src/Carbon/Carbon.php(559): Carbon\Carbon::setLastErrors() #1 /home/host001r/public_html/wp-content/plugins/wedevs-project-manager/vendor/nesbot/carbon/src/Carbon/Carbon.php(606): Carbon\Carbon->__construct() #2 /home/host001r/public_html/wp-content/plugins/wedevs-project-manager/db/seeds/RoleTableSeeder.php(29): Carbon\Carbon::now() #3 /home/host001r/public_html/wp-content/plugins/wedevs-project-manager/core/Installer/Installer.php(11): RoleTableSeeder->run() #4 /home/host001r/public_html/wp-content/plugins/wedevs-project-manager/core/WP/Frontend.php(63): WeDevs\PM\Core\Installer\Installer->do_install() #5 /home/host001r/public_html/wp-content/plugins/wedevs-project-manager/core/WP/Frontend.php(58): WeDevs\PM\Core\WP\Frontend->run_install() #6 /home/host001r/public_html/wp-includes/class-wp-hook.php(324): WeDevs\PM\Core\WP\Frontend->install() #7 /home/host001r/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #8 /home/host001r/public_html/wp-includes/plugin.php(517): WP_Hook->do_action() #9 /home/host001r/public_html/wp-admin/plugins.php(194): do_action() #10 {main} thrown in /home/host001r/public_html/wp-content/plugins/wedevs-project-manager/vendor/nesbot/carbon/src/Carbon/Carbon.php on line 927

**Comment by Rubaiyat-E-Mohammad** [comment]
Could not regenerate
